#pragma once
#include <iostream>
#include"../Library/Lib.h"
using namespace std;
using namespace Truong;

void menu392(int **a, int m, int n);
void HoanVi2Dong392(int **a, int m, int n, int d1, int d2);
void HoanVi2Cot393(int **a, int m, int n, int c1, int c2);
void DichXuongTheoCot(int **a, int m, int n, int c);
void DichXuongTheoCot394(int **a, int m, int n);
void DichLenTheoCot(int **a, int m, int n, int c);
void DichLenTheoCot395(int **a, int m, int n);
void DichTraiTheoDong(int **a, int m, int n, int d);
void DichTraiTheoDong396(int **a, int m, int n);
void DichPhaiTheoDong(int **a, int m, int n, int d);
void DichPhaiTheoDong397(int **a, int m, int n);
void DichPhaiTheoBien398(int **a, int m, int n);
void DichTraiTheoBien399(int **a, int m, int n);
void XoaDong400(int **a, int &m, int n, int d);
void XoaCot401(int **a, int m, int &n, int c);
void XoayMaTran90DoTheoKimDongHo402(int **&a, int &m, int &n);
void XoayMaTran180DoTheoKimDongHo403(int **a, int m, int n);
void XoayMaTran270DoTheoKimDongHo404(int **&a, int &m, int &n);
void ChieuGuongDocMaTran405(int **a, int m, int n);
void ChieuGuongNgangMaTran406(int **a, int m, int n);
void SapXepDong407(int **a, int m, int n, int d);
void SapXepDong408(int **a, int m, int n, int dong);
void SapXepCot409(int **a, int m, int n, int cot);
void SapXepCot410(int **a, int m, int n, int cot);
void XuatChan411(int **a, int m, int n);
void XuatNguyenTo412(int **a, int m, int n);
void SapXep413(int **a, int m, int n);
void SapXep414(int **a, int m, int n);
void SapXepDungMangPhu415(int **a, int m, int n);
void SapXepKhongDungMangPhu415(int **a, int m, int n);
void SapXepSoDuongDungMangPhu416(int **a, int m, int n);
void SapXepSoDuongKhongDungMangPhu416(int **a, int m, int n);
void SapXepSoChanDungMangPhu417(int **a, int m, int n);
void SapXepSoChanKhongDungMangPhu417(int **a, int m, int n);
void SapXepAmTangDuongGiam418(int **a, int m, int n);
void SapXepChanTangLeGiam419(int **a, int m, int n);
void SapXepBienTang420(int **a, int m, int n);
void SapXepBienDuongTang421(int **a, int m, int n);
int TongDong(int **a, int m, int n, int dong);
void SapXepTheoTongDong422(int **a, int m, int n);
void SapXepMaTranXoanOc423(int **a, int m, int n);
void SapXepMTranZicZac424(int **a, int m, int n);
void XuatSoAmGiam425(int **a, int m, int n);
void XayDungMaTranB426(int **a, int ma, int na, int **b, int mb, int nb);
void XayDungMaTranB427(int **a, int ma, int na, int **b);
int DemDuongXungQuanh(int **a, int m, int n, int i, int j);
void XayDungMaTranB428(int **a, int m, int n, int **b);
